window.changeLang=function(b){b=b.options[b.selectedIndex].value;try{var c=document.querySelector('head>link[href$="'+b+'"]').getAttribute("hreflang");localStorage.setItem("preferred-langauge",c)}catch(f){}window.location.href=b};function g(b){var c=document.getElementById("content-area");if(c)for(b=c.getBoundingClientRect().height+b,b=40*Math.floor((b-64)/40)+64+"px",c=document.querySelectorAll("a.navbar-prev, a.navbar-next"),p=0;p<c.length;++p)c[p].style.height=b}
function r(b,c){c||(c="default");for(var f=document.getElementsByClassName(b),e=0;e<f.length;e++){for(var h=f.item(e),l="default",k=0;l!=c&&k<h.childNodes.length;k++)-1!==h.childNodes[k].className.indexOf(c)&&(l=c);h.className=h.className.replace(new RegExp(" ?"+b+"_[a-z0-9]*","g"),"");h.className=h.className+" "+b+"_"+l}g(0)}
function u(b){b.preventDefault();typename=/\b([a-z]*_tabs)\b/.exec(this.parentElement.parentElement.className)[0];type=this.parentElement.className.replace(/ .*$/,"");try{localStorage.setItem(typename,type)}catch(c){}b=this.getBoundingClientRect().top;r(typename,type);window.scrollTo(0,this.getBoundingClientRect().top-b+window.pageYOffset)}
function v(b){for(var c=this;!c.classList.contains("booksidebar");)c=c.parentElement;var f=c.children[1],e=f.children[0].getBoundingClientRect(),e=e.bottom-e.top;c.classList.contains("open")?(c.classList.remove("open"),f.style.maxHeight=0,g(0-e),this.setAttribute("title","Click to open")):(b||f.classList.add("notrans"),c.classList.add("open"),f.style.maxHeight=e+"px",this.setAttribute("title","Click to close"),b?window.setTimeout(function(){g(0)},1E3):(g(0),f.offsetHeight,f.classList.remove("notrans")))}
for(var w=document.querySelectorAll("div.booksidebar>h2.title, .booksidebar-close"),p=0;p<w.length;p++)w.item(p).onclick=v;function x(){var b=document.getElementById(window.location.hash.substr(1));b&&b.classList.contains("booksidebar")&&!b.classList.contains("open")&&v.call(b)}""!=location.hash&&x();window.onhashchange=x;g(0);r("db_tabs",localStorage.getItem("db_tabs"));r("lang_tabs",localStorage.getItem("lang_tabs"));
for(var y=document.querySelectorAll("dl.db_tabs>dt>a, dl.lang_tabs>dt>a"),p=0;p<y.length;p++)y.item(p).onclick=u;var z=document.body;z.className=z.className+" js";(function(){function b(d){return encodeURIComponent(d).replace(/[!'()*]/g,function(d){return"%"+d.charCodeAt(0).toString(16)})}function c(d,b){var c=document.createElement("iframe");c.setAttribute("src",d);c.setAttribute("allowtransparency","true");c.setAttribute("frameborder","0");c.setAttribute("scrolling","no");c.setAttribute("width",b);c.setAttribute("height","20");return c}function f(d){0<d.length&&((0,d.splice(0,1)[0])(),setTimeout(function(d){return function(){return f(d)}}(d),17))}function e(d,
b){for(var c="switch "+b,e=document.querySelectorAll("ul.ssp ."+d),k=[],m=0;m<e.length;++m){var n=e[m].getAttribute("data-ssp-variant")||"default",t=e[m].getAttribute("data-ssp-args"),q=e[m].querySelector(".switch");"off"===b?e[m].onclick=h:e[m].onclick=null;q.className=c;q=e[m].querySelector(".plugin");q.innerHTML="";"on"==b?(n=l[d][n](t),k.push(function(d,b){return function(){d.appendChild(b);return d.firstChild}}(q,n))):l[d].off&&l[d].off()}f(k)}function h(d){d.cancelBubble&&(d.cancelBubble=!0);
d.stopPropagation&&d.stopPropagation();d.preventDefault&&d.preventDefault();for(d=d.target.parentNode;"LI"!=d.tagName&&(d=d.parentNode););var b="on";-1===d.querySelector(".switch").className.indexOf("off")&&(b="off");e(d.className,b);return!1}for(var l={twitter:{tweet:function(){return c("//platform.twitter.com/widgets/tweet_button.html?url="+b(document.location.href)+"&text="+b(document.title)+"&lang="+document.documentElement.lang+"&dnt=true",90)},"default":function(d){return c("//platform.twitter.com/widgets/follow_button.html?lang="+
document.documentElement.lang+"&screen_name="+b(d)+"&show_count=true&show_screen_name=true&size=m",250)}},reddit:{"default":function(){var d=b(document.title),e=b(document.location.href);return c("//redditstatic.s3.amazonaws.com/button/button1.html?newwindow=1&width=120&title="+d+"&url="+e,120)}},hackernews:{"default":function(){var d=b(document.title),e=b(document.location.href);return c("//hn-button.herokuapp.com?count=horizontal&title="+d+"&url="+e,90)}},xing:{"default":function(){var d=document.createElement("div");
d.setAttribute("data-type","XING/Share");d.setAttribute("data-counter","right");var b=document.createElement("script");b.setAttribute("src","https://www.xing-share.com/js/external/share.js");var c=document.createElement("div");c.appendChild(d);c.appendChild(b);return c}},linkedin:{"default":function(){var b=document.createElement("script");b.setAttribute("src","https://platform.linkedin.com/in.js");b.innerHTML="lang: en_US";var c=document.createElement("script");c.setAttribute("type","IN/Share");
c.setAttribute("data-counter","right");var e=document.createElement("div");e.appendChild(b);e.appendChild(c);return e},off:function(){delete window.a}}},k=document.querySelectorAll("ul.ssp .switch"),n=0;n<k.length;++n)k[n].onclick=h;for(var t in l)e(t,"off")})();
